language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - echo "Starting the app"
  - python app.py &
  - echo "Testing the app"
  - curl http://localhost:5000/metadata
  - curl http://localhost:5000
  - curl http://127.0.0.1:5000
  - python API_Testing.py
  - netstat -an | grep 5000