language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - echo "API testing"

after_script:
  # start the web app
  - |
    python app.py &
    APP_PID=$!
  - curl localhost:5000/metadata