language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - echo "Starting the app"
  - python app.py &
  - echo "Testing the app"
  - python API_Testing.py